fixtures:
  repositories:
    puppetlabs-stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppetlabs-concat:  "https://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    asterisk: "#{source_dir}"
